[package]
name = "aurora_protos"
version = "0.1.0"
edition = "2024"

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true

[build-dependencies]
tonic-build = { version = "0.10", features = ["prost"] }